thread_src = ../thread.c ../list.c 


ticket_seller:
	gcc $(thread_src) ticket_seller.c -o ticket_seller.exe -pthread  -I../

reader_writer:
	gcc $(thread_src) reader_writer.c -o reader_writer.exe -pthread  -I../

water:
	gcc $(thread_src) water.c -o water.exe -pthread  -I../

dining_philosophers:
	gcc $(thread_src) dining_philosophers.c -o dining_philosophers.exe -pthread  -I../
