yy(0,                    0, 0,  0,      0,           0,        0)
xx(FLOAT,                1, 0,  0,      0,           CHAR,     "float")
xx(DOUBLE,               2, 0,  0,      0,           CHAR,     "double")
xx(CHAR,                 3, 0,  0,      0,           CHAR,     "char")
xx(SHORT,                4, 0,  0,      0,           CHAR,     "short")
xx(INT,                  5, 0,  0,      0,           CHAR,     "int")
xx(UNSIGNED,             6, 0,  0,      0,           CHAR,     "unsigned")
xx(POINTER,              7, 0,  0,      0,           CHAR,     0)
xx(VOID,                 8, 0,  0,      0,           CHAR,     "void")
xx(STRUCT,               9, 0,  0,      0,           CHAR,     "struct")
xx(UNION,               10, 0,  0,      0,           CHAR,     "union")
xx(FUNCTION,            11, 0,  0,      0,           CHAR,     0)
xx(ARRAY,               12, 0,  0,      0,           CHAR,     0)
xx(ENUM,                13, 0,  0,      0,           CHAR,     "enum")
xx(LONG,                14, 0,  0,      0,           CHAR,     "long")
xx(CONST,               15, 0,  0,      0,           CHAR,     "const")
xx(VOLATILE,            16, 0,  0,      0,           CHAR,     "volatile")
yy(0,                   42,13,MUL,multree,             ID,     "*")
yy(0,                   43,12,ADD,addtree,             ID,     "+")
yy(0,                   44, 1,  0,      0,            ',',     ",")
yy(0,                   45,12,SUB,subtree,             ID,     "-")
yy(0,                   46, 0,  0,      0,            '.',     ".")
yy(0,                   47,13,DIV,multree,            '/',     "/")
yy(0,                   48, 0,SUB,subtree,             ID,     "--")
yy(0,                   49, 0,  0,      0,          DEREF,     "->")
yy(0,                   50, 5,AND,andtree,         ANDAND,     "&&")
yy(0,                   51, 4, OR,andtree,           OROR,     "||")
yy(0,                   52,10, LE,cmptree,            LEQ,     "<=")
